# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#Executar sempre que tiver um novo código na branch main
trigger:
- CI_CD

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- state: Tests
  displayName: 'execution tests'
  jobs: 
  - job: Tests
    displayName: 'tests with jest'
    pool: 
      vmImage: ubuntu-latest
    steps: 
    - task: Npm@1
      command: 'install'
      workingDir: .
    - task: Npm@1
      command: 'run dev'
    
#- stage: Build
#  displayName: 'build image docker'
#  jobs:
#  - job: Build
#    displayName: Build
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: login
#        containerRegistry: 
