# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#Executar sempre que tiver um novo código na branch main
trigger:
- CI_CD

pool: 
  vmImage: 'ubuntu-latest'

variables: 
  localDockerfile: './docker/build/Dockerfile'

steps: 
- task: Docker@2
  displayName: docker build -f $(localDockerfile) -t jonasflorencio/dialogflow-sheets .




